# Generated by Django 3.1 on 2020-08-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
