# Generated by Django 3.1 on 2020-08-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200830_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
