# Generated by Django 3.1 on 2020-08-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
