# Generated by Django 3.1 on 2020-08-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_entry_file_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Papers',
        ),
    ]
