# Generated by Django 3.1 on 2020-09-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'papers',
            },
        ),
    ]
