# Generated by Django 3.1 on 2020-09-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
