# Generated by Django 3.1 on 2020-09-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_paper_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='fileupload',
            field=models.FileField(upload_to='media'),
        ),
    ]
