# Generated by Django 3.1 on 2020-09-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200904_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={},
        ),
        migrations.RemoveField(
            model_name='paper',
            name='slug',
        ),
    ]
