# Generated by Django 3.1 on 2020-09-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200904_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='fileupload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
