# Generated by Django 3.1 on 2020-09-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200904_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=50)),
                ('book_upload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='file_upload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
