# Generated by Django 3.1 on 2020-09-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200905_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Che3Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Che4Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cs2Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cs3Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cs4Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cve2Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cve3Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cve4Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ece2Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ece3Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ece4Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ee2Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ee3Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ee4Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='firstyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='It2Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='It3Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='It4Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Me2Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Me3Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Me4Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Paper',
            new_name='Che2Paper',
        ),
    ]
