# Generated by Django 3.1 on 2020-09-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200906_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='abcd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('fileupload', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
