# Generated by Django 3.1 on 2020-09-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_abcd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abcd',
        ),
    ]
