# Generated by Django 3.1 on 2020-09-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_abcd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebooks',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='ebooks',
            name='bookimage',
            field=models.ImageField(default='', upload_to='book/images'),
        ),
    ]
