# Generated by Django 3.1 on 2020-09-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200907_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('book_upload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Guiproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Text', models.TextField()),
                ('file_upload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pythonproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Text', models.TextField()),
                ('file_upload', models.FileField(null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='Webdevlopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Text', models.TextField()),
                ('file_upload', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Entry',
            new_name='Cproject',
        ),
        migrations.AlterModelOptions(
            name='cproject',
            options={},
        ),
    ]
