# Generated by Django 3.1 on 2020-09-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200907_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ccodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pythonproject',
            options={},
        ),
    ]
